version: "3.8"
services:
  mc:
    build: .
    container_name: fabric-server
    environment:
      - EULA=true
      - OFFLINE=true
      - JAVA_XMS=2G
      - JAVA_XMX=4G
    # Используем host network, чтобы порт 25565 всегда был доступен без публикации
    network_mode: host
    volumes:
      - ./world:/server/world
      - ./logs:/server/logs
      - ./config:/server/config
      - ./mods:/server/mods
    restart: unless-stopped
